services:
  gitlab-reporter:
    build: .
    volumes:
      - ./config:/app/config:ro
      - ./output:/app/output
      - ./src:/app/src
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
      sh -c "echo 'Using release tag: ${GITLAB_RELEASE_TAG}' && python -m src.main $${GITLAB_RELEASE_TAG}"
    # "echo 'Using release tag: $${GITLAB_RELEASE_TAG}' && python -m src.main $${GITLAB_RELEASE_TAG}"
